# Generated by Django 4.1.3 on 2022-11-17 04:25

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_image',
            field=models.ImageField(
                default='default.jpg', upload_to='img/todo/'),
        ),
    ]
